# Generated by Django 3.0.5 on 2021-05-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=20)),
                ('numero_identificacion', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
