# Generated by Django 3.0.5 on 2021-05-05 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='riego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.TimeField(default=datetime.datetime(2021, 5, 5, 18, 53, 31, 972525))),
                ('hora', models.TimeField(default=datetime.datetime(2021, 5, 5, 18, 53, 31, 972525))),
            ],
        ),
    ]
