# Generated by Django 3.0.5 on 2021-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_riego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riego',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='riego',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
